id: IFF9C43C5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:38:36+00:00'
last_modified: '2022-06-07T12:24:10.936666+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC299
  title: 'དགག་གཞག་དང་དཀྱེལ་ཡངས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    1C92:
      image_group_id: I2PD19622
      title: ''
      total_pages: 298
      order: 1
      base_file: 1C92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
