id: P000591
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:50.919792
source_metadata:
  id: bdr:W1AC299
  title: 'དགག་གཞག་དང་དཀྱེལ་ཡངས། '
  author: ''
  volumes:
    5666dfe0fcd140eeb654e90179f56917:
      image_group_id: I2PD19622
      title: ''
      volume_number: 1
      total_pages: 298
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
