id: P000591
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC299
  title: 'དགག་གཞག་དང་དཀྱེལ་ཡངས། '
  author: ''
  volumes:
    5666dfe0fcd140eeb654e90179f56917:
      image_group_id: I2PD19622
      title: ''
      volume_number: 1
      total_pages: 298
